title: Altitude
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: cyan
palettes:
  cyan:
    sass:
      accent2: '#4cabb1'
      accent3: '#69c7ad'
      accent4: '#fed586'
  purple:
    sass:
      accent2: '#656dba'
      accent3: '#7183cd'
      accent4: '#eb8585'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
